// Subjects shown in the admin "Open a Paper" dropdown.
// WAEC_SUBJECTS / JAMB_SUBJECTS: flat lists used by the admin dropdown.
// WAEC_CATEGORIES / JAMB_CATEGORIES: the same subjects grouped for the
// front-end's subject-browsing pages (not used yet — ready for later).

export const WAEC_SUBJECTS = [
  "English Language",
  "General Mathematics",
  "Civic Education",
  "Biology",
  "Chemistry",
  "Physics",
  "Agricultural Science",
  "Further Mathematics",
  "Animal Husbandry",
  "Fisheries",
  "Health Education",
  "Physical Education",
  "Financial Accounting",
  "Commerce",
  "Economics",
  "Marketing",
  "Insurance",
  "Business Management",
  "Office Practice",
  "Data Processing",
  "Book Keeping",
  "Store Management",
  "Store Keeping",
  "Salesmanship",
  "Principles of Cost Accounting",
  "Literature-in-English",
  "Government",
  "History",
  "Geography",
  "Christian Religious Studies (CRS)",
  "Islamic Studies (IRS)",
  "French",
  "Arabic",
  "Hausa",
  "Igbo",
  "Yoruba",
  "Edo",
  "Efik",
  "Ibibio",
  "Technical Drawing",
  "Applied Electricity",
  "Basic Electricity",
  "Basic Electronics",
  "Electronics",
  "Engineering Science",
  "Computer Studies",
  "Auto Mechanics",
  "Auto Electrical Work",
  "Electrical Installation and Maintenance Work",
  "Building Construction",
  "Block Laying, Bricklaying and Concrete Works",
  "Carpentry and Joinery",
  "Plumbing and Pipe Fitting",
  "Welding and Fabrication",
  "Woodwork",
  "Machine Woodworking",
  "Radio, Television and Electronics Work",
  "Air-Conditioning and Refrigeration",
  "Foods and Nutrition",
  "Home Management",
  "Clothing and Textiles",
  "Catering Craft Practice",
  "Garment Making",
  "Cosmetology",
  "Dyeing and Bleaching",
  "Visual Art",
  "Music",
  "Photography",
  "Graphic Design",
  "Painting and Decorating",
  "Sculpture",
  "Ceramics",
  "Textiles",
  "Picture Making",
  "Tourism",
  "Mining",
  "Forestry",
  "Horticulture",
  "Farm Mechanisation",
  "Furniture Making",
  "Leatherwork",
  "Jewellery",
  "Printing Craft Practice",
  "Upholstery",
  "Automobile Parts Merchandising",
];

export const JAMB_SUBJECTS = [
  "Use of English",
  "Agricultural Science",
  "Arabic",
  "Art (Fine Art)",
  "Biology",
  "Chemistry",
  "Christian Religious Studies (CRS)",
  "Commerce",
  "Computer Studies",
  "Economics",
  "French",
  "Geography",
  "Government",
  "Hausa",
  "History",
  "Home Economics",
  "Igbo",
  "Islamic Studies (IRS)",
  "Literature-in-English",
  "Mathematics",
  "Music",
  "Physical and Health Education",
  "Physics",
  "Principles of Accounts",
  "Yoruba",
];

export const WAEC_CATEGORIES = [
  {
    name: "Core WAEC Subjects",
    subjects: ["English Language", "General Mathematics", "Civic Education"],
  },
  {
    name: "Science",
    subjects: [
      "Biology",
      "Chemistry",
      "Physics",
      "Agricultural Science",
      "Further Mathematics",
      "Animal Husbandry",
      "Fisheries",
      "Health Education",
      "Physical Education",
    ],
  },
  {
    name: "Commercial",
    subjects: [
      "Financial Accounting",
      "Commerce",
      "Economics",
      "Marketing",
      "Insurance",
      "Business Management",
      "Office Practice",
      "Data Processing",
      "Book Keeping",
      "Store Management",
      "Store Keeping",
      "Salesmanship",
      "Principles of Cost Accounting",
    ],
  },
  {
    name: "Arts",
    subjects: [
      "Literature-in-English",
      "Government",
      "History",
      "Geography",
      "Christian Religious Studies (CRS)",
      "Islamic Studies (IRS)",
      "Civic Education",
      "Economics",
    ],
  },
  {
    name: "Languages",
    subjects: [
      "English Language",
      "French",
      "Arabic",
      "Hausa",
      "Igbo",
      "Yoruba",
      "Edo",
      "Efik",
      "Ibibio",
    ],
  },
  {
    name: "Technical/Vocational",
    subjects: [
      "Technical Drawing",
      "Applied Electricity",
      "Basic Electricity",
      "Basic Electronics",
      "Electronics",
      "Engineering Science",
      "Computer Studies",
      "Data Processing",
      "Auto Mechanics",
      "Auto Electrical Work",
      "Electrical Installation and Maintenance Work",
      "Building Construction",
      "Block Laying, Bricklaying and Concrete Works",
      "Carpentry and Joinery",
      "Plumbing and Pipe Fitting",
      "Welding and Fabrication",
      "Woodwork",
      "Machine Woodworking",
      "Radio, Television and Electronics Work",
      "Air-Conditioning and Refrigeration",
      "Tourism",
      "Mining",
      "Forestry",
      "Horticulture",
      "Farm Mechanisation",
      "Furniture Making",
      "Leatherwork",
      "Jewellery",
      "Printing Craft Practice",
      "Upholstery",
      "Automobile Parts Merchandising",
    ],
  },
  {
    name: "Home Economics",
    subjects: [
      "Foods and Nutrition",
      "Home Management",
      "Clothing and Textiles",
      "Catering Craft Practice",
      "Garment Making",
      "Cosmetology",
      "Dyeing and Bleaching",
    ],
  },
  {
    name: "Creative Arts",
    subjects: [
      "Visual Art",
      "Music",
      "Photography",
      "Graphic Design",
      "Painting and Decorating",
      "Sculpture",
      "Ceramics",
      "Textiles",
      "Picture Making",
    ],
  },
];

export const JAMB_CATEGORIES = [
  { name: "Compulsory Subject", subjects: ["Use of English"] },
  {
    name: "Science",
    subjects: ["Agricultural Science", "Biology", "Chemistry", "Physics", "Mathematics"],
  },
  {
    name: "Social Sciences & Commercial",
    subjects: ["Commerce", "Economics", "Geography", "Government", "Principles of Accounts"],
  },
  {
    name: "Arts & Humanities",
    subjects: [
      "Art (Fine Art)",
      "Christian Religious Studies (CRS)",
      "History",
      "Islamic Studies (IRS)",
      "Literature-in-English",
      "Music",
    ],
  },
  {
    name: "Languages",
    subjects: ["Arabic", "French", "Hausa", "Igbo", "Yoruba"],
  },
  {
    name: "Other Subjects",
    subjects: ["Computer Studies", "Home Economics", "Physical and Health Education"],
  },
];